apiVersion: v1
kind: Pod
metadata:
  name: noport-pod
  labels:
    name: node-port
spec:  
  containers:
    - name: no-port-container1
      image: pbadhe34/my-apps:app4
      ports:
        - containerPort: 8090

    - name: no-port-container2
      image: pbadhe34/my-apps:app4
      ports:
        - containerPort: 8090
